### PR TITLE
Fixes 3215: Add module_hotfixes flag for repositories

### PR DESCRIPTION
**Pull request by ezr-ondrej**
## Summary

Add flag for disabling modularity filtering on repository basis.

## Testing steps

Create a repository with 'module_hotfix' set to true or false,  Fetching the repository should show it set to true or false depending on what you set it to.  Existing repos should be set to false, and new repos should default to false.

A snapshot's generated repo config should have it set to 0 or 1 depending on if the repo is set to false or true

### CODE REVIEW

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMS-3205

**Comment by jlsherrill** [comment]
⚠️ This task currently requires qe-approval, but this PR does not fully resolve the task.  Please contact QE to determine appropriate testing required.

**Comment by jlsherrill** [comment]
[test]

**Review by rverdile — COMMENTED** [review]
I think [this needs to be updated as well](https://github.com/content-services/content-sources-backend/blob/main/pkg/models/repository_configuration.go#L34-L47), in order to update ModulesHotfixes from true -> false

**Comment by jlsherrill** [comment]
good point, it probably should!  i'll add it

**Review by rverdile — APPROVED** [review]
lgtm

**Comment by swadeley** [comment]
Hi, I created a repo without setting the new flag. 

`In [1]:      repo = dict(
   ...:            snapshot=True,
   ...:            name='fedoratest-snapshot-true',
   ...:            url='https://stephenw.fedorapeople.org/multirepos/6/repo08'
   ...:       )`

The repo was created with flag set to false as expected:
`In [3]: app.content_sources.rest_client.repositories_api.get_repository('db230aac-5c31-4715-a6a5-2fc35309b212')['module_hotfixes']
Out[3]: False`

Created second repo:

`In [5]:      repo = dict(
   ...:            snapshot=True,
   ...:            name='fedoratest-snapshot-true-two',
   ...:            module_hotfixes=True,
   ...:            url='https://stephenw.fedorapeople.org/multirepos/7/repo09'
   ...:       )
`

`In [7]: app.content_sources.rest_client.repositories_api.get_repository('276a6717-07cb-4987-a3cc-346d60985b10')['module_hotfixes']
Out[7]: True
`


```
In [12]: response = app.content_sources.rest_client.repositories_api.get_repo_configuration_file('276a6717-07cb-4987-a3cc-346d60985b10', 'b8541748
    ...: -4a9d-49d2-bc5e-cbe675eff514')
2023-12-05 07:18:32.442 [    INFO] [iqe.base.rest_client] REST: METHOD=GET, request_id=yAAziKEgaWSpgrzedPHiVbSXgaqCaMQK, params=[]

In [13]: import json
    ...: from pprint import pprint

In [14]: pprint(response)
('[fedoratest_snapshot_true_two]\n'
 'name=fedoratest-snapshot-true-two\n'
 'baseurl=https://env-ephemeral-1kp5cq.apps.c-rh-c-eph.8p0c.p1.openshiftapps.com/pulp/content/0206b201/276a6717-07cb-4987-a3cc-346d60985b10/509a7aa6-592a-44f8-831f-69db8741b92e/\n'
 'module_hotfixes=1\n'
 'gpgcheck=0\n'
 'repo_gpgcheck=0\n'
 'enabled=1\n'
 'gpgkey=\n')
```

**Comment by ezr-ondrej** [comment]
Thank you all for taking it over the finish line! :tada:

**Comment by jlsherrill** [comment]
this is now in prod!

**Pull request merged**
