### PR TITLE
Fixes 3942: valid meta_key shows no gpg key found

### PR DESCRIPTION
**Pull request by xbhouse**
## Summary

Adds the request body to the api spec for `/repository_parameters/external_gpg_key/`. This was missing and is needed for QE to test validation of gpg keys when fetching from a remote repo.

## Testing steps

- Add a repository (QE example [here](https://issues.redhat.com/browse/HMS-3942) is using this one: https://jlsherrill.fedorapeople.org/fake-repos/signed/) 
- Fetch the gpg key from this URL: https://jlsherrill.fedorapeople.org/fake-repos/signed/GPG-KEY.gpg
```
POST /repository_parameters/external_gpg_key/

Request:
{
     "url": "https://jlsherrill.fedorapeople.org/fake-repos/signed/GPG-KEY.gpg"
}

Response:
{
    "gpg_key": "-----BEGIN PGP PUBLIC KEY BLOCK-----\n\nmQINBGPhWqgBEACnFSBzQlJ1ilLhS/toT46iJqInMQFtQz...-----END PGP PUBLIC KEY BLOCK-----\n"
}    
```
- Using the gpg key from the previous response, validate the gpg key for the repository
```
POST /repository_parameters/validate/

Request:
[
  {
    "gpg_key": "-----BEGIN PGP PUBLIC KEY BLOCK-----\n\nmQINBGPhWqgBEACnFS...",
    "metadata_verification": true,
    "name": "test1",
    "url": "https://jlsherrill.fedorapeople.org/fake-repos/signed/",
    "uuid": "1c90d2e1-642b-409f-a3ee-256e1a3e6d78"
  }
]

Response:
[
    {
        "name": {
            "skipped": false,
            "valid": true,
            "error": ""
        },
        "url": {
            "skipped": false,
            "valid": true,
            "error": "",
            "http_code": 200,
            "metadata_present": true,
            "metadata_signature_present": false
        },
        "gpg_key": {
            "skipped": false,
            "valid": true,
            "error": ""
        }
    }
]
```
## Checklist

- [ ] Tested with snapshotting feature disabled and pulp server URL not configured if appropriate

### CODE REVIEW

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMS-3942

**Review by jlsherrill — APPROVED** [review]
good catch!

**Comment by swadeley** [comment]
Hi

I tried:

`app.content_sources.rest_client.gpg_key_api.fetch_gpg_key(dict(url="https://jlsherrill.fedorapeople.org/fake-repos/signed/GPG-KEY.gpg"))
`
and

`app.content_sources.rest_client.gpg_key_api.fetch_gpg_key({"url": "https://jlsherrill.fedorapeople.org/fake-repos/signed/GPG-KEY.gpg"})`


but get

`HTTP response body: {"errors":[{"status":400,"detail":"Bad Request"}]}
`

**Comment by swadeley** [comment]
Hi

If I create a repo with a key I can download that:
```
In [18]: app.content_sources.rest_client.repositories_api.get_gpg_key_file('bf5b5ddf-6cdf-454b-95c9-a37f25b031c3')
2024-06-21 13:30:07.510 [    INFO] [iqe.base.rest_client] REST: METHOD=GET, request_id=<>, params=[]
Out[18]: '-----BEGIN PGP PUBLIC KEY BLOCK-----\n\nmQINBGP<snip><snip>uQy8Gk0M=\n=Avdh\n-----END PGP PUBLIC KEY BLOCK-----\n'
```

Confusingly the attribute_map says:

```
In [19]: app.content_sources.rest_client.repositories_api.get_gpg_key_file.attribute_map
Out[19]: {'uuid': 'uuid'}
```

**Comment by swadeley** [comment]
Hi @xbhouse , yes, that fixed it. Thank you.

```
In [1]: app.content_sources.rest_client.gpg_key_api.fetch_gpg_key({'url':'http://jlsherrill.fedorapeople.org/fake-repos/signed/GPG-KEY.gpg'})

2024-06-21 15:41:19.119 [    INFO] [iqe.base.rest_client] REST: METHOD=POST, request_id=<>, params=[]
Out[1]: 
{'gpg_key': '-----BEGIN PGP PUBLIC KEY BLOCK-----\n'
            '\n'
            'mQINBGPhWqgBEACnFSBzQlJ1ilLhS/toT46iJqInMQFtQzQgexR6/XKNfvovqwzH\n'

```

**Pull request merged**
