### PR TITLE
Fixes 1117: use newer yummy for hashicorp repos

### PR DESCRIPTION
**Pull request by jlsherrill**
## Summary
Allows introspection of hashicorp repos
## Testing steps

Create a repo with url of 'https://rpm.releases.hashicorp.com/RHEL/9/x86_64/stable/'
Wait for it to be introspected.

Requires https://github.com/content-services/yummy/pull/10 to be merged and tagged.

### CODE REVIEW

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMS-1117

**Review by rverdile — APPROVED** [review]
lgtm

**Comment by swadeley** [comment]
Working now, thank you.

**Pull request merged**
