### PR TITLE
Refs 3125: allow delete repo during introspect/snapshot

### PR DESCRIPTION
**Pull request by rverdile**
## Summary
This changes the behavior of the delete and bulk delelete repository API endpoints to allow deletion if a snapshot is in progress. If a snapshot is in progress, the snapshot task is canceled. The introspect task is also canceled.

The corresponding frontend PR is here: https://github.com/content-services/content-sources-frontend/pull/269

## Testing steps
1. Create or bulk create repositories. It's easiest to do this in the UI.
2. While the status is pending, delete the repositories.
3. You should find that the running or queued (introspect or snapshot) tasks are canceled, and the repositories are deleted.

## Checklist

- [ ] Tested with snapshotting feature disabled and pulp server URL not configured if appropriate

### CODE REVIEW

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMS-3125

**Comment by jlsherrill** [comment]
⚠️ This task currently requires qe-approval, but this PR does not fully resolve the task.  Please contact QE to determine appropriate testing required.

**Comment by xbhouse** [comment]
if i add a repository without snapshots enabled, and delete the repo during introspection, i'm seeing the delete-repository-snapshots task still be added to the queue and completed. is this expected?

**Comment by xbhouse** [comment]
other than that one question, this looks good and works well!

**Comment by rverdile** [comment]
yep, that task runs whether there's snapshots or not

**Comment by rverdile** [comment]
If someone enabled snapshots, created a repo, then disabled snapshots, we'd still want to clean up the snapshots on deletion.

**Comment by xbhouse** [comment]
got it, makes sense! thanks for explaining

**Review by xbhouse — APPROVED** [review]

**Comment by swadeley** [comment]
It works, yay, thank you.

**Pull request merged**
