### PR TITLE
Refs 121: introspect one public repo on startup

### PR DESCRIPTION
**Pull request by jlsherrill**
This introspects a single repositroy at startup such that
QE can better test integration points

This repo would get introspected once a day as it is

### CODE REVIEW

**Comment by jlsherrill** [comment]
⚠️ This task currently requires qe-approval, but this PR does not fully resolve the task.  Please contact QE to determine appropriate testing required.

**Review by rverdile — APPROVED** [review]
tested and I can see that the repository was introspected

**Comment by rverdile** [comment]
should this have gotten the "Ready For QE" flag automatically?

**Comment by jlsherrill** [comment]
yeah, its because its a Refs PR and no fixes Pr, which isn't something handled very well.

Multiple GH prs per issue makes things complicated ;)

**Pull request merged**
