### PR TITLE
Build: Use upstream docker image, drop zookeeper

### PR DESCRIPTION
**Pull request by jlsherrill**
## Summary

This moves us to the official kafka container, as well as drops zookeeper.  Zookeeper is no longer needed, and in fact will removed from the kafka project entirely at 4.0 

## Testing steps

```
make compose-clean compose-up
make run
```

in another terminal
```
KAFKA_TOPICS=platform.content-sources.template make kafka-topic-consume
```

and then create a content template:

```
####
POST http://localhost:8000/api/content-sources/v1.0/templates/
x-rh-identity: eyJpZGVudGl0eSI6eyJvcmdfaWQiOiI5IiwgInR5cGUiOiJVc2VyIiwidXNlciI6eyJ1c2VybmFtZSI6ImZvbyJ9LCJhY2NvdW50X251bWJlciI6ImZvbyIsImludGVybmFsIjp7Im9yZ19pZCI6IjkifX19Cg==
Content-Type: application/json

{
 "name":"FOO",
  "repository_uuids": []
}
```

You should see the message make it to the kafka consume command:

```
Partition:0	content-type:application/cloudevents+json	null	{"specversion":"1.0","id":"ddcf8416-c153-4386-b1c8-9bf338eca641","source":"urn:redhat:source:console:app:repositories","type":"com.redhat.console.repositories.template-created","subject":"urn:redhat:subject:console:rhel:template-created","datacontenttype":"application/json","time":"2024-04-18T11:33:51.38720455Z","data":[{"uuid":"7bdbf4d9-04de-4405-ba4b-1d6505c61477","name":"FOO","org_id":"9","description":"","arch":"","version":"","date":"0001-01-01T00:00:00Z","repository_uuids":[]}],"redhatorgid":"9"}

```

## Checklist

- [ ] Tested with snapshotting feature disabled and pulp server URL not configured if appropriate

### CODE REVIEW

**Comment by jlsherrill** [comment]
if we do want to merge this, i'd want to build an automated way to rebuild the container  'make kafka' or something

**Review by Andrewgdewar — DISMISSED** [review]

**Comment by xbhouse** [comment]
looks good on my end!

```
Partition:0	content-type:application/cloudevents+json	null	{"specversion":"1.0","id":"f6ec129c-256b-4ab5-b1df-a7d3dda9fe24","source":"urn:redhat:source:console:app:repositories","type":"com.redhat.console.repositories.template-created","subject":"urn:redhat:subject:console:rhel:template-created","datacontenttype":"application/json","time":"2024-04-18T18:47:42.587779Z","data":[{"uuid":"d0044364-8544-49cf-89bf-7a16c741d257","name":"test","org_id":"17684632","description":"description","arch":"aarch64","version":"8","date":"0001-01-01T00:00:00Z","repository_uuids":["34c37f8c-2d95-47bb-8c8e-e95f3ba14f3e"]}],"redhatorgid":"17684632"}
```

**Comment by xbhouse** [comment]
i did see this warning when creating the topic, but platform.content-sources.introspect doesn't have an underscore so not sure why it came up: 

```
WARNING: Due to limitations in metric names, topics with a period ('.') or underscore ('_') could collide. To avoid issues it is best to use either, but not both.
```

**Comment by xbhouse** [comment]
we should probably update the README too since we wouldn't need to build the container anymore

**Comment by jlsherrill** [comment]
fixed the readme.  That warning is fine, we don't necessarily control the topic name format, and just went with the console dot standard.

**Review by xbhouse — APPROVED** [review]
ack from me! @Andrewgdewar when you get a chance can you check if the kafka changes work for you?

**Comment by jlsherrill** [comment]
@Andrewgdewar says he is fine with @xbhouse's testing and to go ahead and merge

**Pull request merged**
