### PR TITLE
Fixes 4281: remove 8-stream from public repos

### PR DESCRIPTION
**Pull request by jlsherrill**
## Summary

and make repos removed from the external_repos.json file no longer public

## Testing steps

1. on main run `make repos-import`
2. connect to the db and query 8-stream public repos:
```
make db-cli-connect
# select public, url from repositories  where url ilike '%8-stream%';
```
3.  Check out this PR, re-run `make repos-import`
4. re-query the query and make sure the 8-stream repos are no longer public
5. query the 9-stream repos and make sure they are still public
```
# select public, url from repositories  where url ilike '%9-stream%';
```

## Checklist

- [ ] Tested with snapshotting feature disabled and pulp server URL not configured if appropriate

### CODE REVIEW

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMS-4281

**Comment by swadeley** [comment]
QE ACK, tested OK

**Review by xbhouse — APPROVED** [review]
works and looks good!

**Pull request merged**
