### PR TITLE
Refs 183: Add iqe marker expression

### PR DESCRIPTION
**Pull request by mshriver**
only run tests marked for API in the pr_checks

### CODE REVIEW

**Review by Andrewgdewar — APPROVED** [review]
Fix the title yah hooligan. Ack!

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMSCONTENT-183

**Comment by jlsherrill** [comment]
⚠️ This task currently requires qe-approval, but this PR does not fully resolve the task.  Please contact QE to determine appropriate testing required.

**Pull request merged**
