### PR TITLE
Fixes 4055: treat filter/page param parse as info

### PR DESCRIPTION
**Pull request by jlsherrill**
## Summary

Changes filter/pagination parsing errors as info level logging instead of error

## Testing steps

perform a request:
GET http://localhost:8000/api/content-sources/v1.0/templates/?limit=a

watch your server, it should show logging at INFO

## Checklist

- [ ] Tested with snapshotting feature disabled and pulp server URL not configured if appropriate

### CODE REVIEW

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMS-4055

**Comment by xbhouse** [comment]
i see `11:40AM ERR ../../go/pkg/mod/github.com/content-services/lecho/v3@v3.5.2/middleware.go:179 > error="error: code=500, title=Error listing templates, detail=ERROR: invalid byte sequence for encoding \"UTF8\": 0x00 (SQLSTATE 22021) \n"` when sending a request like `/templates/?name=%00`

do you need to make these updates to the templates handler as well? and maybe the task_info handler, though invalid syntax (`/tasks/?status=%00`) logs as DBG there so i'm not sure

**Comment by jlsherrill** [comment]
Good catch!  The template actually had a function to detect this, but 1) it wasn't being called & 2) it wasn't checking for a query error properly, this should be fixed!

**Review by xbhouse — APPROVED** [review]
lgtm!

**Pull request merged**
