### PR TITLE
Fixes 128: build a container image on each pr

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMSCONTENT-128

**Comment by mshriver** [comment]
For the record, the scripts added by #47 will do this as well, building into the cloudservices org via Jenkins. But it requires appsre onboarding and app-interface acceptance, which has been slow and blocking.

**Comment by jlsherrill** [comment]
and you can see the results here:  https://quay.io/repository/jlsherri/content-sources?tab=tags   pr-1

**Review by swadeley — APPROVED** [review]
ACK

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/14751782

**Pull request merged**
