### PR TITLE
Fixes 3654: Remove UUID from public repos

### PR DESCRIPTION
**Pull request by Andrewgdewar**
## Summary

Simply removes the UUID from the public_repos response.

## Testing steps

- Get /public_repositories/ list, check that the UUID is no longer present.

### CODE REVIEW

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMS-3654

**Comment by xbhouse** [comment]
lgtm! thanks for the addition to the readme too :)

**Review by xbhouse — APPROVED** [review]

**Comment by swadeley** [comment]
Hi

lgtm

```
In [3]: app.content_sources.rest_client.public_repositories_api.list_public_repositories(limit=4)
2024-02-27 18:45:26.209 [    INFO] [iqe.base.rest_client] REST: METHOD=GET, request_id=aAXhVmMvfcvhvzBfRngxhBNlUPYNoJwB, params=[('limit', 4)]
Out[3]: 
{'data': [{'last_introspection_error': '',
           'last_introspection_time': '',
           'last_success_introspection_time': '',
           'last_update_introspection_time': '',
           'package_count': 0,
           'status': 'Pending',
           'url': 'http://mirror.centos.org/centos/8-stream/AppStream/x86_64/os/'},
          {'last_introspection_error': '',
           'last_introspection_time': '',
           'last_success_introspection_time': '',
           'last_update_introspection_time': '',
           'package_count': 0,
           'status': 'Pending',
           'url': 'http://mirror.centos.org/centos/8-stream/BaseOS/x86_64/os/'},
          {'last_introspection_error': '',
           'last_introspection_time': '',
           'last_success_introspection_time': '',
           'last_update_introspection_time': '',
           'package_count': 0,
           'status': 'Pending',
           'url': 'http://mirror.centos.org/centos/8-stream/extras/x86_64/os/'},
          {'last_introspection_error': '',
           'last_introspection_time': '',
           'last_success_introspection_time': '',
           'last_update_introspection_time': '',
           'package_count': 0,
           'status': 'Pending',
           'url': 'http://mirror.stream.centos.org/9-stream/AppStream/x86_64/os/'}],
 'links': {'first': '/api/content-sources/v1/public_repositories/?limit=4&offset=0',
           'last': '/api/content-sources/v1/public_repositories/?limit=4&offset=52',
           'next': '/api/content-sources/v1/public_repositories/?limit=4&offset=4'},
 'meta': {'count': 56, 'limit': 4, 'offset': 0}}

In [4]: 


```

**Pull request merged**
