### PR TITLE
Build: pr_check, use insights-stage as ref-env

### PR DESCRIPTION
**Pull request by jrusz**
This will deploy the apps using whatever is in stage which is where PRs are deployed after being merged.

## Checklist

- [ ] Tested with snapshotting feature disabled and pulp server URL not configured if appropriate

### CODE REVIEW

**Comment by jlsherrill** [comment]
[test]

**Comment by jlsherrill** [comment]
[test]

**Review by swadeley — APPROVED** [review]
ACK

**Pull request merged**
