### PR TITLE
Fixes 2918: use parent context for cancel test

### PR DESCRIPTION
**Pull request by jlsherrill**
## Summary

This uses a parent context to send the cancel notification for this test.  I suspect the ordering of things executing was causing the cancel trigger to have its context triggered prior to it finishing

## Testing steps
Tests pass

## Checklist

- [x] Tested with snapshotting feature disabled and pulp server URL not configured if appropriate

### CODE REVIEW

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMS-2918

**Review by rverdile — APPROVED** [review]
lgtm!

**Comment by jlsherrill** [comment]
going ahead and merging, as iqe failure is unrelated

**Pull request merged**
