### PR TITLE
Refs 276: Fixes Tag on popular_repositories list api

### PR DESCRIPTION
**Pull request by Andrewgdewar**

### CODE REVIEW

**Review by jlsherrill — APPROVED** [review]

**Comment by jlsherrill** [comment]
will let mike merge :)

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMSCONTENT-276

**Comment by jlsherrill** [comment]
⚠️ This task currently requires qe-approval, but this PR does not fully resolve the task.  Please contact QE to determine appropriate testing required.

**Review by mshriver — APPROVED** [review]
Generated a new client from this and saw the `list_popular_repositories()` only available for popular_repositories, as intended.  The GET continues to work fine.

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMSCONTENT-309

**Comment by mshriver** [comment]
Thanks @Andrewgdewar !

**Pull request merged**
