### PR TITLE
Fixes 140: Create LICENSE

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMSCONTENT-140

**Comment by jlsherrill** [comment]
Built and pushed image for 6dbcce2440f3b91efdf4af3614e225a5dd162315

**Review by Andrewgdewar — APPROVED** [review]
Much License, do we need to add something similar to the frontend?

**Comment by jlsherrill** [comment]
Its already there! (I checked).  I had held off adding it to the backend until i got some feedback from the insights platform, and they finally ended up suggesting this license as a base recommendation

**Review by swadeley — APPROVED** [review]
ACK

**Pull request merged**
