### PR TITLE
Refs 2425: trim error on update

### PR DESCRIPTION
**Pull request by jlsherrill**
## Summary

When setting a limit on the error field, trim existing contents.

## Testing steps
tests pass

### CODE REVIEW

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMS-2425

**Comment by jlsherrill** [comment]
⚠️ This task currently requires qe-approval, but this PR does not fully resolve the task.  Please contact QE to determine appropriate testing required.

**Review by Andrewgdewar — APPROVED** [review]
LGTM!

**Comment by jlsherrill** [comment]
this isn't a qe visible change other than stage being up! merging

**Pull request merged**
