### PR TITLE
Refs 101: update commit format

### PR DESCRIPTION
**Pull request by jlsherrill**
Changes the commit format such that:
* A jira card is now required
* You can use Refs or Fixes to indicate if a PR
  is related to or fully fixes a card
* Adds a github action to validate PR Title

### CODE REVIEW

**Review by swadeley — APPROVED** [review]
ACK

**Comment by jlsherrill** [comment]
updated to drop the '#' symbol, as that can cause confusion since github interprets '#num' as a link to a pr

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMSCONTENT-101

**Review by mshriver — APPROVED** [review]

**Comment by jlsherrill** [comment]
This task currently requires qe-approval, but this PR does not fully resolve the task.  Please contact QE to determine appropriate testing required.

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/14709226

**Pull request merged**
