### PR TITLE
Fixes 3577: creation prevented on previously deleted item

### PR DESCRIPTION
**Pull request by Andrewgdewar**
## Summary

This change updates the unique key value on the templates table to only encompass items that have their "deleted_at" set to null, IE not "soft-deleted". 

Thus preventing a dupe-key error that would present when a previously "soft-deleted" template shared a name with a template that was being created.

## Testing steps

- Create a template, 
- Delete it, 
- Create another template with the same name, 
- Prior to this change, the api would error with "Template with this name already exists".

## Checklist

- [ ] Tested with snapshotting feature disabled and pulp server URL not configured if appropriate

### CODE REVIEW

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMS-3577

**Comment by xbhouse** [comment]
reproduced the error with these steps:

- import RH repos and snapshot all of them (`make repos-import && go run cmd/external-repos/main.go nightly-jobs`)

while those tasks are running:
- create template
- delete template
- create template with name of the one that was just deleted

not seeing this error anymore with your changes :) looks good!

**Review by xbhouse — APPROVED** [review]

**Comment by swadeley** [comment]
Hi

I deployed:
content-sources-backend=pr-573-latest 

but I get error:
`HTTP response body: {"errors":[{"status":400,"title":"Error creating template","detail":"Template with this name already belongs to organization"}]}`


My steps:

```
In [4]: app.content_sources.rest_client.templates_api.create_template(dict(
   ...:    name="my template one",
   ...:    repository_uuids=["daa4e8e4-412b-4052-9654-b7f557b95a72"],
   ...:    description="my first draft",
   ...:    arch="x86_64",
   ...:    version="7"
   ...:    ))
2024-02-15 16:01:00.089 [    INFO] [iqe.base.rest_client] REST: METHOD=POST, request_id=<>, <>, params=[]
Out[4]: 
{'arch': 'x86_64',
 'date': '0001-01-01T00:00:00Z',
 'description': 'my first draft',
 'name': 'my template one',
 'org_id': '16781244',
 'repository_uuids': ['daa4e8e4-412b-4052-9654-b7f557b95a72'],
 'uuid': '7bee45e6-d632-460e-96b9-bd0985a8715e',
 'version': '7'}

In [5]: app.content_sources.rest_client.templates_api.delete_template('7bee45e6-d632-460e-96b9-bd0985a8715e')
2024-02-15 16:01:18.987 [    INFO] [iqe.base.rest_client] REST: METHOD=DELETE, request_id=<>, <>, params=[]

In [6]: app.content_sources.rest_client.templates_api.list_templates(sort_by='name')
2024-02-15 16:01:42.706 [    INFO] [iqe.base.rest_client] REST: METHOD=GET, request_id=<>, <>, params=[('sort_by', 'name')]
Out[6]: 
{'data': [],
 'links': {'first': '/api/content-sources/v1/templates/?limit=100&offset=0&sort_by=name',
           'last': '/api/content-sources/v1/templates/?limit=100&offset=0&sort_by=name'},
 'meta': {'count': 0, 'limit': 100, 'offset': 0}}

In [7]: app.content_sources.rest_client.templates_api.create_template(dict(
   ...:    name="my template one",
   ...:    repository_uuids=["daa4e8e4-412b-4052-9654-b7f557b95a72"],
   ...:    description="my first draft",
   ...:    arch="x86_64",
   ...:    version="7"
   ...:    ))
2024-02-15 16:01:52.448 [    INFO] [iqe.base.rest_client] REST: METHOD=POST, request_id=<>, <>, params=[]

<traceback>

```
```
ApiException: (400)
Reason: Bad Request
```

**Comment by swadeley** [comment]
Hi, going to retest soon.

**Pull request merged**
