### PR TITLE
Refs 1176: run label check after assigning

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Review by swadeley — DISMISSED** [review]
ACK

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMS-1176

**Comment by jlsherrill** [comment]
⚠️ This task currently requires qe-approval, but this PR does not fully resolve the task.  Please contact QE to determine appropriate testing required.

**Review by swadeley — DISMISSED** [review]
ACK 2

**Review by swadeley — DISMISSED** [review]
ACK 3

**Review by swadeley — APPROVED** [review]
ACK 4

**Review by swadeley — DISMISSED** [review]
ACK 5

**Review by swadeley — APPROVED** [review]
ACK 6

**Comment by mshriver** [comment]
rebase after #194

**Review by swadeley — APPROVED** [review]
ACK 7

**Pull request merged**
