### PR TITLE
Refs 4133: add types filter to admin tasks list

### PR DESCRIPTION
**Pull request by rverdile**
## Summary
Adds ability to filter admin tasks by type

## Testing steps
1. Either test using frontend PR or make a request like `GET /admin/tasks/?type=introspect,snapshot`
2. Make sure you've created/deleted some repos and templates so you have a few task types to filter.
3. These are all the task types: https://github.com/content-services/content-sources-backend/blob/main/pkg/config/tasks.go#L4-L9
## Checklist

- [ ] Tested with snapshotting feature disabled and pulp server URL not configured if appropriate

### CODE REVIEW

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMS-4133

**Comment by jlsherrill** [comment]
⚠️ This task currently requires qe-approval, but this PR does not fully resolve the task.  Please contact QE to determine appropriate testing required.

**Review by xbhouse — APPROVED** [review]
tested with API and frontend PR, looks great!

**Comment by swadeley** [comment]
Works great, thank you

https://github.com/content-services/content-sources-frontend/pull/285#issuecomment-2179052469

**Pull request merged**
