### PR TITLE
Refs 173: define internal service

### PR DESCRIPTION
**Pull request by jlsherrill**
This is needed for stage/prod, example here:   https://github.com/RedHatInsights/entitlements-api-go/blob/master/deployment/deploy.yml#L152-L172

### CODE REVIEW

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMSCONTENT-173

**Comment by jlsherrill** [comment]
⚠️ This task currently requires qe-approval, but this PR does not fully resolve the task.  Please contact QE to determine appropriate testing required.

**Review by mshriver — APPROVED** [review]
Looks fine, re-running CI before merge.

**Pull request merged**
