### PR TITLE
Fixes 2582,2425: add account_id to task table, trim error

### PR DESCRIPTION
**Pull request by jlsherrill**
## Summary

Adds account_id to tasks table.  This makes querying by account_id easier and faster.
Note that after this change, any existing tasks will have a null account_id, but since we are still in stage, that is okay.

Change error length to 4000 chars, and auto trim error if its longer than that

I did these in a single PR as they would normally conflict

## Testing steps

1. Deploy this pr and migrate the db
2. Snapshot some repository
3. Use the admin tasks interface
4. filter by account id

Verify nothing is broken, behavior should be the same

Unsure how to test the error length, i wasn't able to reproduce it but the unit test should prove that its solved

### CODE REVIEW

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMS-2583

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMS-2425

**Comment by swadeley** [comment]
Hi, introspection seems to be misbehaving. Repos with `example.com` never finish introspecting. I see three  "delete-repository-snapshots" tasks which have been running for nearly 24 hours.

**Comment by jlsherrill** [comment]
i wasn't able to reproduce, are you able to?

**Comment by swadeley** [comment]
> i wasn't able to reproduce, are you able to?

Hi, I deployed new image and now introspection completes as expected.

Thank you.

**Comment by swadeley** [comment]
> Hi
> 
> I deployed this PR, ran automated tests and made manual check in UI. Works as described, I can filter on account ID, org ID, all works as expected.
> 
> API test result pending.

Tested again and ran all API tests.

Thank you.

**Comment by swadeley** [comment]
@rverdile Merge after your approval.

**Review by rverdile — APPROVED** [review]
tested and lgtm!

**Pull request merged**
