### PR TITLE
Update Dependencies

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by Andrewgdewar** [comment]
Did you delete your go.sum before updating? I find it cleans out old values best that way. Not sure if it's best practice.

**Review by Andrewgdewar — COMMENTED** [review]
After pulling this into my branch and "go get ./..." and "go mod tidy" I see a bit of a different output. 
Did you run tidy on this?

**Comment by jlsherrill** [comment]
good call, updated!

**Review by Andrewgdewar — APPROVED** [review]
No changes when I updated! ACK

**Pull request merged**
