### PR TITLE
Refs 1176: switch to env

### PR DESCRIPTION
**Pull request by jlsherrill**
This reverts commit 167bfd5fbfe264db74b3cc335a6a67b13953c54a.

### CODE REVIEW

**Review by mshriver — APPROVED** [review]

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMS-1176

**Comment by jlsherrill** [comment]
⚠️ This task currently requires qe-approval, but this PR does not fully resolve the task.  Please contact QE to determine appropriate testing required.

**Review by swadeley — APPROVED** [review]
ACK

**Review by mshriver — APPROVED** [review]

**Review by swadeley — APPROVED** [review]
ACK pending rebase

**Comment by mshriver** [comment]
I approve of closing this

**Pull request closed without merging**
