### PR TITLE
Fixes 4398: replace pointy with internal function

### PR DESCRIPTION
**Pull request by jlsherrill**
## Summary

Replace pointy.pointer with a custom function (written from the ground up!) 

## Testing steps

Tests pass

### CODE REVIEW

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMS-4398

**Comment by jlsherrill** [comment]
updated to use new yummy, no reference to pointy anywhere

**Review by rverdile — APPROVED** [review]

**Pull request merged**
