### PR TITLE
Fixes 2367: talk to pulp api directly

### PR DESCRIPTION
**Pull request by jlsherrill**
## Summary
do not go through the web container

## Testing steps
Tests pass?

If you want to further test, test a snapshot in ephemeral and verify the task doesn't fail with this deployment.yaml

### CODE REVIEW

**Review by Andrewgdewar — APPROVED** [review]
ack

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMS-2367

**Comment by jlsherrill** [comment]
updating stage here:  https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/77682

so you can /lgtm once this is merged

**Comment by swadeley** [comment]
Hi

re comment 0

not through the web container refers to this diff:
```
-    value: "http://cs-pulp-web-svc:24880/"
+    value: "http://cs-pulp-api-svc:24817/"
```

**Pull request merged**
