### PR TITLE
Refs 3372: switch to new s3 bucket name

### PR DESCRIPTION
**Pull request by jlsherrill**
## Summary

forgot to rename it in our code

## Checklist

- [ ] Tested with snapshotting feature disabled and pulp server URL not configured if appropriate

### CODE REVIEW

**Review by Andrewgdewar — APPROVED** [review]
Much bucket, very name.

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMS-3372

**Comment by jlsherrill** [comment]
⚠️ This task currently requires qe-approval, but this PR does not fully resolve the task.  Please contact QE to determine appropriate testing required.

**Comment by jlsherrill** [comment]
going ahead and merging to fix stage

**Pull request merged**
