### PR TITLE
Fixes 168: fix api doc for pkg name search

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
regen'ing the docs seemed to update some other stuff... let me see if i can tell why

**Review by mshriver — APPROVED** [review]
@swadeley test for the endpoint uncovered this, thanks @jlsherrill !

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMSCONTENT-168

**Comment by mshriver** [comment]
Local testing of the spec updates was successful, merging this and pushing them to plugin repo to unblock initial tests for search endpoint.

**Pull request merged**
