### PR TITLE
Refs 2486: trigger a manual build

### PR DESCRIPTION
**Pull request by swadeley**
## Summary

Triggering a manual build to see if that will pull in changes from:

load browser config for rbac user (!222) · Merge requests · insights-qe / iqe-content-sources-plugin 

and if that will fix frontend PR checks.

### CODE REVIEW

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMS-2486

**Comment by jlsherrill** [comment]
⚠️ This task currently requires qe-approval, but this PR does not fully resolve the task.  Please contact QE to determine appropriate testing required.

**Review by swadeley — COMMENTED** [review]
lgtm

**Review by rverdile — APPROVED** [review]

**Comment by swadeley** [comment]
Thank you

**Pull request merged**
