### PR TITLE
Refs 280: remove revision column

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
⚠️ This task currently requires qe-approval, but this PR does not fully resolve the task.  Please contact QE to determine appropriate testing required.

**Comment by jlsherrill** [comment]
Note that we'll merge this after https://github.com/content-services/content-sources-backend/pull/154 is merged and gone through stage

**Comment by mshriver** [comment]
Checking #154 in stage before merging this.

**Review by Andrewgdewar — APPROVED** [review]
✅

**Pull request merged**
