### PR TITLE
Fixes 3020: Adding VNC geometry

### PR DESCRIPTION
**Pull request by akhil-jha**
HMS-3020

Relates to https://github.com/RHEnVision/provisioning-backend/pull/751 , https://github.com/osbuild/image-builder/pull/901

### CODE REVIEW

**Comment by akhil-jha** [comment]
@swadeley

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMS-HMS-3020

**Review by mshriver — APPROVED** [review]

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMS-3020

**Pull request merged**
