### PR TITLE
Refs 142: deployment changes for cdn secret

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMSCONTENT-142

**Comment by jlsherrill** [comment]
⚠️ This task currently requires qe-approval, but this PR does not fully resolve the task.  Please contact QE to determine appropriate testing required.

**Comment by avisiedo** [comment]
- Checked that the secret exists.

```sh
oc get secrets/content-sources-certs
NAME                    TYPE     DATA   AGE
content-sources-certs   Opaque   1      37m
```

- Checked that the env var contain the secret value in a rsh opened into the container:

```sh
oc rsh pod/POD_NAME
env | grep RH_CDN_CERT_PAIR
RH_CDN_CERT_PAIR=THE_EXPECTED_VALUE
```

**Review by avisiedo — APPROVED** [review]
I have checked the secret and the content of the variable into the pod deployed exists and match.

LGTM

**Review by swadeley — APPROVED** [review]
ACK

**Pull request merged**
