### PR TITLE
Fixes 209: update base container image

### PR DESCRIPTION
**Pull request by jlsherrill**
and swith to ubi8 micro

### CODE REVIEW

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMSCONTENT-209

**Comment by jlsherrill** [comment]
looked at using micro, but didn't have a trusted ca store... so syncing didn't work :)

**Comment by avisiedo** [comment]
LGTM

- image built and pushed to quay.io
- [Clair](https://github.com/quay/clair) scanner report security scan passed.

**Review by avisiedo — APPROVED** [review]
lgtm

**Pull request merged**
