### PR TITLE
Fixes 4249: Reuse HTTP zest transport

### PR DESCRIPTION
**Pull request by lzap**
Hello, I noticed this small detail - a new transport is created for each zest client, this effectively means that no HTTP connection pooling can be done. Here is an example of the [DefaultTransport](https://cs.opensource.google/go/go/+/refs/tags/go1.22.3:src/net/http/transport.go) from the standard library that is supposed to be reused - it is thread safe.

Easy help, this patch just extracts the variable into the package scope so it can be reused on every new client. In case you are wondering, all those timeouts are coming from the `DefaultTransport` from the standard library plus the `ResponseHeaderTimeout` that was already defined here.

_Edit: I was trying out github.dev, did not go well, force pushed the correct version._

### CODE REVIEW

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMS-4249

**Comment by jlsherrill** [comment]
looks good!  i think you're just missing the 'net' import

**Comment by lzap** [comment]
Sure, rebased.

**Review by jlsherrill — APPROVED** [review]

**Comment by jlsherrill** [comment]
thanks @lzap !

**Pull request merged**
