### PR TITLE
Fixes 4540: cancel template update tasks on delete

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMS-4540

**Comment by jlsherrill** [comment]
Other things this PR needs:
* [ ]  https://github.com/content-services/content-sources-backend/pull/774 merged
* [ ] https://issues.redhat.com/browse/HMS-4478 completed so that this will cancel pending tasks and not just ones already running

**Comment by jlsherrill** [comment]
[test]

**Review by rverdile — APPROVED** [review]
looks good!

**Pull request merged**
