### PR TITLE
Fixes 3600: delete distributions and env on template delete

### PR DESCRIPTION
**Pull request by rverdile**
## Summary
Adds additional actions to the DeleteTemplate task so that the associated pulp distributions and candlepin environment are also deleted.

## Testing steps
1. Create a template with a mix of red hat and custom repositories
2. You can verify the existence of the distributions by browsing to `http://pulp.content:8080/pulp/content/<domain>/templates/<template_uuid>/`
3. You can verify the existence of the environment by GET requesting `http://localhost:8181/candlepin/environments/<env id>`. The env_id is the template_uuid without the hyphens.
4. Delete the template
5. Recheck those endpoints and you should get a 404.

## Checklist

- [ ] Tested with snapshotting feature disabled and pulp server URL not configured if appropriate

### CODE REVIEW

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMS-3600

**Comment by jlsherrill** [comment]
I'm not seeing the distributions  getting deleted.  In fact i never saw a DELETE call to pulp, which makes me think dao.template.GetDistributionHref() is returning  ""  ?  (just a guess)  I did check the payload and it seemed to be there:

```
{"PoolID": "8ad981858fc03bd6018fc06c821e1e03", "TemplateUUID": "09e69d33-e236-4219-bdfe-b1ea2a5bc0d5", "RepoConfigUUIDs": ["73c32f6c-e1ba-4d51-b3de-8cf66f848854", "4d858709-65b2-495f-91fa-28aa7a731654", "9cb8141b-9c73-4152-9fa9-50d3ccbc3966"]}
```

**Comment by rverdile** [comment]
this should work now

**Comment by jlsherrill** [comment]
yep, seems to work great.  Would you mind adding an integration test?   Even if its just with a custom repo (no red hat repos), that would have caught this.

**Comment by rverdile** [comment]
I added to the test here: https://github.com/content-services/content-sources-backend/blob/025902696cfe7856a5acda0c005870f708459b1d/test/integration/update_template_content_test.go#L249-L269

It doesn't catch it because our integration tests don't test the API handler. It was missing the "RepositoryUUIDs" part of the payload.

**Comment by jlsherrill** [comment]
ahhh, i see!

**Review by jlsherrill — APPROVED** [review]

**Pull request merged**
