### PR TITLE
Refs 2711: upgrade to postgres 15

### PR DESCRIPTION
**Pull request by jlsherrill**
## Summary
Upgrade to Postgres 15

## Testing steps
tests pass?

## Checklist

- [x] Tested with snapshotting feature disabled and pulp server URL not configured if appropriate

### CODE REVIEW

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMS-2711

**Comment by jlsherrill** [comment]
⚠️ This task currently requires qe-approval, but this PR does not fully resolve the task.  Please contact QE to determine appropriate testing required.

**Review by rverdile — APPROVED** [review]

**Pull request merged**
