### PR TITLE
Fixes 252: Fix TestRpmList unit test

### PR DESCRIPTION
**Pull request by avisiedo**
Update limit to `-1` into TestRpmList

Signed-off-by: Alejandro Visiedo <avisiedo@redhat.com>

### CODE REVIEW

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMSCONTENT-252

**Comment by avisiedo** [comment]
closing as I was not able to replay again from the `main` branch.

**Comment by jlsherrill** [comment]
i suspect that maybe the problem actually has to do with go 1.18 in the pr https://github.com/content-services/content-sources-backend/pull/125

have we seen it elsewhere?

**Comment by jlsherrill** [comment]
I was actually able to reproduce this locally randomly :)  
I fixed this here:  https://github.com/content-services/content-sources-backend/pull/125/files#diff-73ba5cff26e1cda8426ce77b3206b3b368b202a1ce40582dc8a37f96f23f217b
i think its related to the upgraded of go and deps, its treating limit 0 as actual limit 0, i'm not 100% why it wasn't doing that before

**Pull request closed without merging**
