### PR TITLE
Refs 1203: Initial grafana update for new metrics

### PR DESCRIPTION
**Pull request by jlsherrill**
This includes all metrics except for content_sources_kafka_message_result_total which does not seem to be working correctly

### CODE REVIEW

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMS-1203

**Comment by jlsherrill** [comment]
image
image

**Comment by jlsherrill** [comment]
i wanted to go ahead and get 'something' committed, as i have to redo the work if i get logged out.   
So more work tuning will be done, but i'd vote for just going ahead and merging this and tweaking later

**Review by rverdile — APPROVED** [review]
ack. looks good

**Pull request merged**
