### PR TITLE
Fixes 2398: PulpPropFix

### PR DESCRIPTION
**Pull request by Andrewgdewar**
## Summary

Ongoing PR to fix nil ref in prod

### CODE REVIEW

**Review by mshriver — APPROVED** [review]

**Comment by jlsherrill** [comment]
https://issues.redhat.com/browse/HMS-2398

**Comment by jlsherrill** [comment]
⚠️ This task currently requires qe-approval, but this PR does not fully resolve the task.  Please contact QE to determine appropriate testing required.

**Comment by mshriver** [comment]
marking draft to block merge while unit test is resolved.

**Comment by mshriver** [comment]
This introduced a submodule for pulp-oci-images inadvertently

**Pull request merged**
